config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'admin/index'
  get 'users/index'
  resources :direction_statuses
  resources :response_measures
  resources :violations
  resources :reasons
  scope '(:locale)', locale: /en|ru/ do
    get 'dashboard/report'

    devise_for :users, skip: [:sessions]
    unauthenticated do
      as :user do
        get '', to: 'custom_sessions#new', as: :new_user_session
        post '', to: 'custom_sessions#create', as: :user_session
      end
    end

    authenticated do
      as :user do
        delete '', to: 'custom_sessions#destroy', as: :destroy_user_session
      end
    end

    authenticate :user, ->(u) { u.is_admin == true } do
      resources :checks
      resources :people
      resources :organizations
      resources :reports
      resources :inspectors
      resources :categories
      resources :users
      resource  :admin
    end

    authenticate :user, ->(u) { u.is_admin == false } do
      resources :checks
      resources :people
      resources :organizations
      resources :reports
      resources :inspectors
      resources :categories
    end

    resources :checks, only: %i[index show]
    resources :people, only: %i[index show]
    get 'dashboard/index'
    get 'dashboard/info'

    root 'dashboard#index'
    resources :organizations, only: %i[index show]
    resources :reports, only: %i[index show]
    resources :inspectors, only: %i[index show]
  end
end

app/models/check.rb
# frozen_string_literal: true

# model describe all check in ai system
class Check < ApplicationRecord
  belongs_to :inspector
  # belongs_to :user
  has_and_belongs_to_many :organizations
  has_and_belongs_to_many :people

  has_and_belongs_to_many :categories
  has_and_belongs_to_many :reasons
  has_and_belongs_to_many :violations
  has_and_belongs_to_many :response_measures
  has_and_belongs_to_many :direction_statuses
  validates :amount, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 999_999_999, only_integer: true }
  validate :check_start_less_than_check_finish, :check_finish_more_than_check_start, :check_finish_less_than_check_remark_destroy

  def status
    return 'secondary' if under_control?

    if check_remark_destroy > Time.zone.now.to_date && check_remark_destroy < (Time.zone.now.to_date - 1.week)
      'warning'
    elsif check_remark_destroy > (Time.zone.now.to_date - 1.week)
      'success'
    else
      'danger'
    end
  end

  private

  def check_start_less_than_check_finish
    errors.add(:check_start, 'check start less than check finish') unless check_start < check_finish
  end

  def check_finish_more_than_check_start
    errors.add(:check_finish, 'check finish more than check start') unless check_start < check_finish
  end

  def check_finish_less_than_check_remark_destroy
    errors.add(:check_remark_destroy, 'check finish less than check_remark_destroy') unless check_finish < check_remark_destroy
  end

  def under_control?
    control
  end
end

app/controllers/checks_controller.rb
# frozen_string_literal: true

# ChecksController
class ChecksController < ApplicationController
  before_action :set_check, only: %i[show edit update destroy]

  # GET /checks
  # GET /checks.json
  def index
    @search = Check.ransack(params[:q])
    @checks = @search.result(distinct: true)
    @inspectors = Inspector.full_list
  end

  # GET /checks/1
  # GET /checks/1.json
  def show; end

  def new
    @check = Check.new
  end

  # GET /checks/1/edit
  def edit
    authorize @check
  end

  # POST /checks
  # POST /checks.json
  def create
    @check = Check.new(check_params)

    respond_to do |format|
      if @check.save
        format.html { redirect_to @check, notice: t(:check_created) }
        format.json { render :show, status: :created, location: @check }
      else
        format.html { render :new }
        format.json { render json: @check.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /checks/1
  # PATCH/PUT /checks/1.json
  def update
    respond_to do |format|
      if @check.update(check_params)
        format.html { redirect_to @check, notice: t(:check_updated) }
        format.json { render :show, status: :ok, location: @check }
      else
        format.html { render :edit }
        format.json { render json: @check.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checks/1
  # DELETE /checks/1.json
  def destroy
    @check.destroy
    authorize(@check, :destroy?)
    respond_to do |format|
      format.html { redirect_back fallback_location: :back, notice: t(:check_destroyed) }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_check
    @check = Check.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def check_params
    params.require(:check).permit(
      :title_check,
      :amount,
      :checks_number,
      :check_start,
      :check_remark_destroy,
      :check_finish,
      :inspector_id,
      :executive,
      { organization_ids: [] },
      { person_ids: [] },
      { response_measure_ids: [] },
      { reason_ids: [] },
      { violation_ids: [] },
      { category_ids: [] },
      { direction_status_ids: [] },
      :direction_author,
      :direction_where,
      :case_number,
      :number_of_volumes,
      :for_office,
      :control
    )
  end
end

app/views/checks/_form.html.erb
<%= simple_form_for @check do |f| %>
  <%= f.error_notification %>
  <%= f.input :title_check, placeholder: t(:title_check), label: t(:title_check) %>
  <%= f.input :amount, placeholder: t(:amount), label: t(:amount), input_html: {min: 1, value: 1} %>
  <%= f.input :checks_number, placeholder: t(:checks_number), label: t(:checks_number) %>
  <%= f.input :check_start, label: t(:check_start) %>
  <%= f.input :check_finish, label: t(:check_finish) %>
  <%= f.input :check_remark_destroy, label: t(:check_remark_destroy) %>
  <%= f.association :inspector, label: t(:executive), label_method: :full_name %>
  <%= f.input :executive, placeholder: t(:inspectors), label: t(:inspectors) %>
  <%= f.association :organizations, as: :select, label_method: :name, label: t(:checks_organizations) %>
  <%= f.association :people, as: :select, label_method: :last_name, label: t(:checks_people_organizations) %>
  <%= f.association :response_measures, label_method: :name, label: t(:response_measures) %>
  <%= f.association :reasons, label_method: :name, label: t(:reasons) %>
  <%= f.association :violations, label_method: :name, label: t(:violations) %>
  <%= f.association :categories, label_method: :name, label: t(:categories) %>
  <%= f.association :direction_statuses, label_method: :name, label: t(:direction_statuses) %>
  <%= f.input :direction_author, label: t(:direction_author) %>
  <%= f.input :direction_where, label: t(:direction_where) %>
  <%= f.input :case_number, placeholder: t(:case_number), label: t(:case_number) %>
  <%= f.input :number_of_volumes, placeholder: t(:number_of_volumes), label: t(:number_of_volumes) %>
  <%= f.input :for_office, label: t(:for_office) %>
  <%= f.input :control, label: t(:control) %>
  <%= f.button :submit, t(:save), class: "btn btn-outline-inverse" %>
<% end %>
<br>

app/views/checks/edit.html.erb
<h1><%= t(:editing_check) %></h1>

<%= render 'form', check: @check %>

<%= link_to t(:show), @check %>
|
<%= link_to t(:back), :back %>

app/views/checks/index.html.erb
<h1><%= t(:checks) %></h1>
<%= render partial: "searchbar", locals: {search: @search, path: new_check_path, text: t(:new_check), search_hash: :case_number_cont} %>
<br>
<% @checks.each do |check| %>
  <div class="card border-<%= check.status %> mb-3">
    <div class="card-body">
      <span class="badge float-sm-right"><%= l check.updated_at, format: :short %></span>
      <h5 class="card-title"><%= "\# #{check.case_number} - #{check.title_check}" %></h5>
      <h6 class="card-subtitle mb-2 text-muted"><%= "#{check.check_start} / #{check.check_finish} / #{check.check_remark_destroy}" %></h6>
      <p class="card-text"> <%= "#{t(:amount)} - #{check.amount}" %> </p>
      <div class="collapse" id="collapse_list_<%= check.id %>">
        <p class="card-text"> <%= "#{t(:checks_number)} - #{check.checks_number}" %> </p>
        <p class="card-text"> <%= "#{t(:direction_status)} - #{check.direction_status}" %> </p>
        <p class="card-text"> <%= "#{t(:number_of_volumes)} - #{check.number_of_volumes}" %> </p>
        <p class="card-text"> <%= "#{t(:for_office)} - #{check.for_office}" %> </p>
        <p class="card-text"> <%= "#{t(:executive)} - #{check.executive}" %> </p>
        <p class="card-text"> <%= "#{t(:control)} - #{check.control}" %> </p>
        <p class="card-text"> <%= "#{t(:direction_author)} - #{check.direction_author}" %> </p>
        <p class="card-text"> <%= "#{t(:direction_where)} - #{check.direction_where}" %> </p>
      </div>
      <a data-toggle="collapse" href="#collapse_list_<%= check.id %>">+</a>
      <%= link_to check.inspector.full_name, inspector_path(check.inspector_id), class: 'card-link' %>
      <%= link_to '->', check_path(check), class: 'card-link' %>
    </div>
  </div>
  <br>
<% end %>

app/views/checks/new.html.erb
<h1><%= t(:new_check) %></h1>

<%= render 'form', check: @check %>

<%= link_to t(:back), checks_path %>

app/views/checks/show.html.erb
<div class="well well-sm">
  <p>
    <strong><%= t(:title_check) %>:</strong>
    <%= @check.title_check %>
  </p>

  <p>
    <strong><%= t(:amount) %>:</strong>
    <%= @check.amount %>
  </p>

  <p>
    <strong><%= t(:checks_number) %>:</strong>
    <%= @check.checks_number %>
  </p>

  <p>
    <strong><%= t(:check_start) %>:</strong>
    <%= @check.check_start %>
  </p>

  <p>
    <strong><%= t(:check_finish) %>:</strong>
    <%= @check.check_finish %>
  </p>

  <p>
    <strong><%= t(:check_remark_destroy) %>:</strong>
    <%= @check.check_remark_destroy %>
  </p>

  <p>
    <strong><%= t(:reason) %>:</strong>
  <ul>
    <% @check.reasons.each do |var| %>
      <li class=""><%= var.name %></li>
    <% end %>
  </ul>
  </p>

  <p>
    <strong><%= t(:category) %>:</strong>
  <ul>
    <% @check.categories.each do |var| %>
      <li class=""><%= var.name %></li>
    <% end %>
  </ul>
  </p>

  <p>
    <strong><%= t(:violation) %>:</strong>
  <ul>
    <% @check.violations.each do |var| %>
      <li class=""><%= var.name %></li>
    <% end %>
  </ul>
  </p>

  <p>
    <strong><%= t(:response_measure) %>:</strong>
  <ul>
    <% @check.response_measures.each do |var| %>
      <li class=""><%= var.name %></li>
    <% end %>
  </ul>
  </p>

  <p>
    <strong><%= t(:direction_author) %>:</strong>
    <%= @check.direction_author %>
  </p>

  <p>
    <strong><%= t(:direction_where) %>:</strong>
    <%= @check.direction_where %>
  </p>

  <p>
    <strong><%= t(:direction_status) %>:</strong>
    <%= @check.direction_status %>
  </p>

  <p>
    <strong><%= t(:executive) %>:</strong>
    <%= @check.inspector.full_name %>
  </p>

  <p>
    <strong><%= t(:checks_organizations) %>:</strong>
  </p>
  <ul>
    <% @check.organizations.each do |var| %>
      <li class=""><%= var.name %></li>
    <% end %>
  </ul>

  <p>
    <strong><%= t(:checks_people_organizations) %>:</strong>
  </p>
  <ul>
    <% @check.people.each do |var| %>
      <li class=""><%= var.last_name %></li>
    <% end %>
  </ul>

  <p>
    <strong><%= t(:case_number) %>:</strong>
    <%= @check.case_number %>
  </p>

  <p>
    <strong><%= t(:number_of_volumes) %>:</strong>
    <%= @check.number_of_volumes %>
  </p>

  <p>
    <strong><%= t(:for_office) %>:</strong>
    <%= @check.for_office %>
  </p>

  <p>
    <strong><%= t(:control) %>:</strong>
    <%= @check.control %>
  </p>
</div>
<% if current_user.is_admin == true %>
  <%= link_to t(:edit), edit_check_path(@check) %>
  |
<% end %>
<%= link_to t(:back), :back %>