config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'admin/index'
  get 'users/index'
  resources :direction_statuses
  resources :response_measures
  resources :violations
  resources :reasons
  scope '(:locale)', locale: /en|ru/ do
    get 'dashboard/report'

    devise_for :users, skip: [:sessions]
    unauthenticated do
      as :user do
        get '', to: 'custom_sessions#new', as: :new_user_session
        post '', to: 'custom_sessions#create', as: :user_session
      end
    end

    authenticated do
      as :user do
        delete '', to: 'custom_sessions#destroy', as: :destroy_user_session
      end
    end

    authenticate :user, ->(u) { u.is_admin == true } do
      resources :checks
      resources :people
      resources :organizations
      resources :reports
      resources :inspectors
      resources :categories
      resources :users
      resource  :admin
    end

    authenticate :user, ->(u) { u.is_admin == false } do
      resources :checks
      resources :people
      resources :organizations
      resources :reports
      resources :inspectors
      resources :categories
    end

    resources :checks, only: %i[index show]
    resources :people, only: %i[index show]
    get 'dashboard/index'
    get 'dashboard/info'

    root 'dashboard#index'
    resources :organizations, only: %i[index show]
    resources :reports, only: %i[index show]
    resources :inspectors, only: %i[index show]
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :set_locale
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
    Rails.application.routes.default_url_options[:locale] = I18n.locale
  end

  def default_url_options(options = {})
    { locale: I18n.locale }.merge options
  end

  def user_not_authorized
    flash[:alert] = I18n.t 'controllers.access_denied'
    redirect_back(fallback_location: root_path)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/application/_card.html.erb
<div class="col-lg-3 col-md-6 col-xs-12">
  <div class="card text-center">
    <div class="card-body">
      <h6 class="card-title"></h6>
      <i class="fa <%= icon %> fa-5x"></i>
      <p class="card-text"><%= "#{title} #{count}" %></p>
    </div>
    <div class="card-footer text-muted">
      <%= link_to t(:expand), path %>
    </div>
  </div>
  <br>
</div>

app/views/application/_edit_destroy.html.erb
<% if current_user.is_admin == true %>
  <td><%= link_to '<i class="fa fa-pencil" aria-hidden="true"></i>'.html_safe, edit_obj %></td>
  <td><%= link_to '<i class="fa fa-trash-o" aria-hidden="true"></i>'.html_safe, obj, method: :delete, data: {confirm: t(:are_you_sure)} %></td>
<% end %>

app/views/application/_navbar_login.html.erb
<div class="collapse navbar-collapse" id="navbarsExampleDefault">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item"><%= link_to t(:checks), checks_path, class: 'nav-link' %></li>
    <li class="nav-item"><%= link_to t(:reports), reports_path, class: 'nav-link' %></li>
    <li class="nav-item"><%= link_to t(:statistic), dashboard_report_path, class: 'nav-link' %></li>
    <% if current_user.is_admin == true %>
      <li class="nav-item"><%= link_to t(:admin_panel), admin_index_path, class: 'nav-link' %></li>
    <% end %>
    <li class="nav-item dropdown">
      <a href="#" class="nav-link dropdown-toggle" id="dropdown_left" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">...</a>
      <div class="dropdown-menu" aria-labelledby="dropdown_left">
        <%= link_to t(:inspectors), inspectors_path, class: 'dropdown-item' %>
        <%= link_to t(:people), people_path, class: 'dropdown-item' %>
        <%= link_to t(:organization), organizations_path, class: 'dropdown-item' %>
        <%= link_to t(:help), dashboard_info_path, class: 'dropdown-item' %>
      </div>
    </li>
  </ul>
  <ul class="navbar-nav ml-auto">
    <li class="dropdown">
      <a href="#" class="nav-link dropdown-toggle" id="dropdown_right" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">...</a>
      <div class="dropdown-menu" aria-labelledby="dropdown_right">
        <% if I18n.locale == :en %>
          <%= link_to t(:language), {locale: :ru}, class: 'dropdown-item' %>
        <% elsif I18n.locale == :ru %>
          <%= link_to t(:language), {locale: :en}, class: 'dropdown-item' %>
        <% end %>
      </div>
    </li>
    <li class="nav-item"><%= link_to t(:sign_out), destroy_user_session_path, class: 'nav-link', :method => :delete %></li>
  </ul>
</div>

app/views/application/_navbar_logout.html.erb
<div class="collapse navbar-collapse" id="navbarsExampleDefault">
  <ul class="navbar-nav ml-auto">
    <li class="nav-item"><%= link_to t(:sign_in), new_user_session_path, class: 'nav-link' %></li>
  </ul>
</div>

app/views/application/_searchbar.html.erb
<div class="row justify-content-between">
  <div class="col-lg-2">
    <% if current_user.is_admin == true %>
      <div class="input-group-btn">
        <%= link_to text, path, class: 'btn btn-outline-success' %>
      </div>
    <% end %>
  </div>
  <div class="col-lg-3">
    <%= search_form_for search do |f| %>
      <div class="input-group">
        <%= f.text_field search_hash, class: "form-control" %>
        <div class="input-group-append">
          <%= f.submit search_hash, class: "btn btn-outline-secondary", value: t(:search) %>
        </div>
      </div>
    <% end %>
  </div>
</div>