config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'admin/index'
  get 'users/index'
  resources :direction_statuses
  resources :response_measures
  resources :violations
  resources :reasons
  scope '(:locale)', locale: /en|ru/ do
    get 'dashboard/report'

    devise_for :users, skip: [:sessions]
    unauthenticated do
      as :user do
        get '', to: 'custom_sessions#new', as: :new_user_session
        post '', to: 'custom_sessions#create', as: :user_session
      end
    end

    authenticated do
      as :user do
        delete '', to: 'custom_sessions#destroy', as: :destroy_user_session
      end
    end

    authenticate :user, ->(u) { u.is_admin == true } do
      resources :checks
      resources :people
      resources :organizations
      resources :reports
      resources :inspectors
      resources :categories
      resources :users
      resource  :admin
    end

    authenticate :user, ->(u) { u.is_admin == false } do
      resources :checks
      resources :people
      resources :organizations
      resources :reports
      resources :inspectors
      resources :categories
    end

    resources :checks, only: %i[index show]
    resources :people, only: %i[index show]
    get 'dashboard/index'
    get 'dashboard/info'

    root 'dashboard#index'
    resources :organizations, only: %i[index show]
    resources :reports, only: %i[index show]
    resources :inspectors, only: %i[index show]
  end
end

app/models/report.rb
# frozen_string_literal: true

require 'prawn'

class Report < ApplicationRecord
  has_and_belongs_to_many :reasons
  belongs_to :inspector # , dependent: :destroy
  # belongs_to :user
  belongs_to :organization # , dependent: :destroy иначе удаляет больше одной записи
  delegate :name, to: :organization, prefix: true
  validates :title_report, :number, :executive, presence: true
  has_and_belongs_to_many :results

  def create_pdf
    pdf = Prawn::Document.new
    pdf.text "Title: #{title_report}"
    pdf.render
  end
end

app/controllers/reports_controller.rb
# frozen_string_literal: true

# ReportsController
class ReportsController < ApplicationController
  before_action :set_report, only: %i[show edit update destroy]

  # GET /reports
  # GET /reports.json
  def index
    @search = Report.ransack(params[:q])
    @reports = @search.result(distinct: true).sorted
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @inspectors = @report.inspector.full_name
    @organizations = @report.organization_name
    respond_to do |format|
      format.html
      format.json { render :show, location: @report }
      format.pdf do
        send_data @report.create_pdf
      end
    end
  end

  # GET /reports/new
  def new
    @report = Report.new
    @inspectors = Inspector.full_list
    @organizations = Organization.full_list
  end

  # GET /reports/1/edit
  def edit
    @inspectors = Inspector.full_list
    @organizations = Organization.full_list
    authorize @report
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)
    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: t(:report_created) }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: t(:report_updated) }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    authorize(@report, :destroy?)
    respond_to do |format|
      format.html { redirect_back fallback_location: :back, notice: t(:report_destroyed) }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_report
    @report = Report.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def report_params
    params.require(:report).permit(
      :number,
      :title_report,
      :create_report,
      :deadline,
      :inspector_id,
      :organization_id,
      :executive,
      result_ids: [],
      reason_ids: []
    )
  end
end

app/views/reports/_form.html.erb
<%= simple_form_for @report do |f| %>
  <%= f.error_notification %>
  <%= f.input :title_report, placeholder: t(:title_report), label: t(:title_report) %>
  <%= f.input :number, placeholder: t(:number), label: t(:number) %>
  <%= f.input :create_report, label: t(:create_report) %>
  <%= f.input :deadline, label: t(:deadline) %>
  <%= f.association :reasons, label_method: :name, label: t(:reason) %>
  <%= f.association :inspector, label: t(:inspector), label_method: :full_name %>
  <%= f.association :organization, label: t(:organization), label_method: :name %>
  <%= f.association :results, label: t(:result), label_method: :name %>
  <%= f.input :executive, label: t(:executive), placeholder: t(:executive) %>
  <%= f.button :submit, t(:save), class: "btn btn-outline-inverse" %>
<% end %>
<br>

app/views/reports/edit.html.erb
<h1><%= t(:edit_report) %></h1>

<%= render 'form', report: @report %>

<%= link_to t(:show), @report %> |
<%= link_to t(:back), :back %>

app/views/reports/index.html.erb
<h1><%= t(:reports) %></h1>
<%= render partial: "searchbar", locals: {search: @search, path: new_report_path, text: t(:new_report), search_hash: :title_report_cont} %>
<br>
<table class="table">
  <thead>
  <tr>
    <th><%= sort_link @search, :case_number, t(:case_number) %></th>
    <th><%= sort_link @search, :title_report, t(:title_report) %></th>
    <th><%= sort_link @search, :deadline, t(:deadline) %></th>
    <th><%= sort_link @search, :inspector, t(:inspector) %></th>
    <th><%= sort_link @search, :organization, t(:organization) %></th>
    <th><%= sort_link @search, :executive, t(:executive) %></th>
    <% if current_user.is_admin %>
      <th colspan="2"></th>
    <% else %>
      <th colspan="1"></th>
    <% end %>
  </tr>
  </thead>

  <tbody>
  <% @reports.each do |r| %>
    <tr>
      <td><%= link_to r.number, report_path(r) %></td>
      <td><%= link_to r.title_report, report_path(r) %></td>
      <td><%= link_to r.deadline, report_path(r) %></td>
      <td><%= link_to r.inspector.full_name, inspector_path(r.inspector_id) %></td>
      <td><%= link_to r.organization.name, organization_path(r.organization_id) %></td>
      <td><%= link_to r.executive, report_path(r) %></td>
      <td><%= link_to '<i class="fa fa-file-text" aria-hidden="true"></i>'.html_safe, report_path(r, format: :pdf) %></td>
      <%= render partial: "edit_destroy", locals: {obj: r, edit_obj: edit_report_path(r)} %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/reports/new.html.erb
<h1><%= t(:new_report) %></h1>

<%= render 'form', report: @report %>

<%= link_to t(:back), reports_path %>

app/views/reports/show.html.erb
<div class="well well-sm">
  <p>
    <strong><%= t(:case_number) %>:</strong>
    <%= @report.number %>
  </p>
  <p>
    <strong><%= t(:title_report) %>:</strong>
    <%= @report.title_report %>
  </p>
  <p>
    <strong><%= t(:create_report) %>:</strong>
    <%= @report.create_report %>
  </p>
  <p>
    <strong><%= t(:deadline) %>:</strong>
    <%= @report.deadline %>
  </p>
  <p>
    <strong><%= t(:inspector) %>:</strong>
    <%= @inspectors %>
  </p>
  <p>
    <strong><%= t(:organization) %>:</strong>
    <%= @organizations %>
  </p>
  <p>
    <strong><%= t(:executive) %>:</strong>
    <%= @report.executive %>
  </p>
  <p>
    <strong><%= t(:reason) %>:</strong>
  <ul>
    <% @report.reasons.each do |var| %>
      <li class=""><%= var.name %></li>
    <% end %>
  </ul>
  </p>
  <p>
    <strong><%= t(:result) %>:</strong>
  <ul>
    <% @report.results.each do |var| %>
      <li class=""><%= var.name %></li>
    <% end %>
  </ul>
  </p>
</div>
<% if current_user.is_admin == true %>
  <%= link_to t(:edit), edit_report_path(@report) %>
  |
<% end %>
<%= link_to t(:back), :back %>